model: pointMLPSmall
exp_name: null
sampling_input: 
- points
model_input:
- points
use_normals: true
batch_size: 128
test_batch_size: 64
epochs: 250
num_points: 1024
block_size: 2.0
stride: 1.0
min_points: 64
pose_noise: false
n_duplication: 3
pose_noise_range: 0.1
sensor_noise: false
sensor_noise_std: 0.1
voxelize: true
voxel_size: 0.1
normal_radius: 0.1
normalize: true
use_sgd: false
scheduler: step
step: 40
lr: 0.003
momentum: 0.9
manual_seed: null
eval: false
workers: 12
resume: false
model_type: insiou